<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>cbr_fase3</name>
  <version>0.1.0</version>
  <description>Gesture-controlled mission for CBR 2025 fase 3 FSM</description>
  <maintainer email="viniceconp@gmail.com">Vinicius Ceccon</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>cbr_drone_lib</depend>
  <depend>fsm</depend>
  <depend>Eigen3</depend>
  <depend>rclcpp</depend>


  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
