fase1_fsm:
  ros__parameters:
    fictual_home_x: 1.0
    fictual_home_y: -1.0
    fictual_home_z: -0.6 # Remember z points Down

    num_bases: 6.0 # Bases to visit (excluding home)
    known_base_radius: 1.5
    height_to_ground: 0.65
    
    # Dynamic grid parameters
    grid_y_length: -6.0 # Negative -> grid spawns to the left of home
    grid_step_x: 2.0 # Step size in x direction
    grid_num_steps: 3.0 # Number of steps in x direction

    takeoff_height: -2.5
    align_height: -2.0
    max_base_height: -1.5
    mean_base_height: 0.85 # Use positive values for this height

    max_vertical_velocity: 1.2
    max_horizontal_velocity: 1.0
    landing_velocity_max: 0.5
    landing_velocity_min: 0.2

    max_search_time: 30.0
    detection_timeout: 10.0

    position_tolerance: 0.07
    align_tolerance: 0.025

    pid_pos_kp: 1.0
    pid_pos_ki: 0.01
    pid_pos_kd: 0.05
    setpoint: 0.0

fase1_vision:
  ros__parameters:
    timeout: 10.0