# Ground Station

telemetry_handler:
  ros__parameters:
      visualization:
        known_base_radius: 1.5


telemetry_recorder:
  ros__parameters:
    enable: true
    max_duration_minutes: 10
    max_file_size_mb: 1000
    output_directory: "~/frtl_2025_ws/flight_logs/ground_station"

telemetry_dashboard:
  ros__parameters:
    network:
      ping_target: "192.168.0.100"  # Network monitoring target
    topics:
      position: "/telemetry/position"
      drone_status: "/telemetry/drone_status"
      system_health: "/telemetry/system_health" 
      logs: "/telemetry/logs"