# Ground Station

telemetry_handler:
  ros__parameters:
      visualization:
        known_base_radius: 1.5


log_viewer:
  ros__parameters:
    enable_gui: true
    max_displayed_logs: 1000
    auto_scroll: true
    filter_by_level: false

telemetry_recorder:
  ros__parameters:
    enable: true
    max_duration_minutes: 10
    max_file_size_mb: 1000
    output_directory: "/tmp/flight_logs/ground_station"